# Generated by Django 5.0.7 on 2024-10-16 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_percent', models.IntegerField(verbose_name='Процент за мобильное приложение')),
                ('web_percent', models.IntegerField(verbose_name='Процент за веб-сайт')),
                ('min_order_price', models.IntegerField(verbose_name='Минимальная сумма заказа')),
            ],
            options={
                'verbose_name': 'Процент кэшбэка',
                'verbose_name_plural': 'Проценты кэшбэка',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Промокод')),
                ('valid_from', models.DateTimeField(verbose_name='Начало действия')),
                ('valid_to', models.DateTimeField(verbose_name='Конец действия')),
                ('discount', models.IntegerField(help_text='Процент скидки', verbose_name='Скидка')),
                ('active', models.BooleanField(default=False, verbose_name='Активен')),
                ('type', models.CharField(choices=[('%', 'Процент'), ('сом', 'Фиксированная сумма')], max_length=3, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/', verbose_name='Картинка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Контактный номер')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('apartment_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер квартиры')),
                ('entrance', models.CharField(blank=True, max_length=10, null=True, verbose_name='Подъезд')),
                ('floor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Этаж')),
                ('intercom', models.CharField(blank=True, max_length=10, null=True, verbose_name='Домофон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Главный')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=200, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=200, null=True, verbose_name='Долгота')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='Время заказа')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая сумма')),
                ('total_bonus_amount', models.IntegerField(blank=True, null=True, verbose_name='Общая сумма бонусов')),
                ('is_pickup', models.BooleanField(default=False, verbose_name='Самовывоз')),
                ('payment_method', models.CharField(choices=[('card', 'Карта'), ('cash', 'Наличные'), ('online', 'Онлайн')], default='card', max_length=255, verbose_name='Способ оплаты')),
                ('change', models.IntegerField(blank=True, null=True, verbose_name='Сдача')),
                ('order_status', models.CharField(choices=[('pending', 'В ожидании'), ('in_progress', 'В процессе'), ('delivery', 'Доставка'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус заказа')),
                ('order_source', models.CharField(choices=[('mobile', 'Мобильное приложение'), ('web', 'Веб-сайт'), ('unknown', 'Неизвестно')], default='unknown', max_length=10, verbose_name='Источник заказа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('user_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.useraddress')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.promocode')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size_id', models.IntegerField(blank=True, null=True, verbose_name='Выбранный размер')),
                ('size_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер')),
                ('color_id', models.IntegerField(blank=True, null=True, verbose_name='Выбранный цвет')),
                ('color_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название цвета')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('is_bonus', models.BooleanField(default=False, verbose_name='Бонусный продукт')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order', verbose_name='Заказ')),
                ('product_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productsize', verbose_name='Размер продукта')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
            },
        ),
    ]
