# Generated by Django 5.0.7 on 2024-10-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='user_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.DeleteModel(
            name='DistancePricing',
        ),
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='TelegramBotToken',
        ),
        migrations.DeleteModel(
            name='WhatsAppChat',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='topping',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер телефона'),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
