# Generated by Django 5.0.7 on 2024-10-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
    ]
