# Generated by Django 5.0.7 on 2024-10-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='link',
            field=models.URLField(default=1, verbose_name='Ссылка на карту'),
            preserve_default=False,
        ),
    ]
