# Generated by Django 5.0.7 on 2024-11-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_warehouse_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentcashback',
            name='delivery',
            field=models.BooleanField(default=True, verbose_name='Доставка'),
        ),
        migrations.AddField(
            model_name='percentcashback',
            name='payment_card',
            field=models.BooleanField(default=True, verbose_name='Оплата онлайн'),
        ),
        migrations.AddField(
            model_name='percentcashback',
            name='payment_cash',
            field=models.BooleanField(default=True, verbose_name='Оплата наличными'),
        ),
        migrations.AddField(
            model_name='percentcashback',
            name='pick_up',
            field=models.BooleanField(default=True, verbose_name='Самовывоз'),
        ),
    ]
