# Generated by Django 5.0.7 on 2024-10-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
    ]
