# Generated by Django 5.0.7 on 2024-10-14 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_email_remove_order_full_name_and_more'),
        ('product', '0003_remove_form_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.size', verbose_name='Выбранный размер'),
            preserve_default=False,
        ),
    ]
