# Generated by Django 5.0.7 on 2024-10-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
