# Generated by Django 5.0.7 on 2024-10-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Выбранный размер'),
        ),
    ]
