# Generated by Django 5.0.7 on 2024-10-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderitem_size_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название выбранного размера'),
        ),
    ]
