# Generated by Django 5.0.7 on 2024-10-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderitem_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер'),
        ),
    ]
