# Generated by Django 5.0.7 on 2024-10-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderitem_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Выбранный цвет'),
        ),
    ]
