# Generated by Django 5.0.7 on 2024-10-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderitem_color_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('apartment_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер квартиры')),
                ('entrance', models.CharField(blank=True, max_length=10, null=True, verbose_name='Подъезд')),
                ('floor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Этаж')),
                ('intercom', models.CharField(blank=True, max_length=10, null=True, verbose_name='Домофон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Главный')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=200, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=200, null=True, verbose_name='Долгота')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
    ]
