# Generated by Django 5.0.7 on 2024-10-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcolor',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='formcolor',
            name='name_kk',
            field=models.CharField(max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='formcolor',
            name='name_ky',
            field=models.CharField(max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='formcolor',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Цвет'),
        ),
    ]
