# Generated by Django 5.0.7 on 2024-10-16 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name': 'Вариант продукта', 'verbose_name_plural': 'Вариант продуктов'},
        ),
        migrations.RemoveField(
            model_name='size',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productsize',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_images', to='product.productsize', verbose_name='Вариант'),
        ),
    ]
