# Generated by Django 5.0.7 on 2024-10-11 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='type_kk',
        ),
        migrations.RemoveField(
            model_name='attributefield',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_kk',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='color',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='form',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='formcategory',
            name='description_kk',
        ),
        migrations.RemoveField(
            model_name='formcategory',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='formcolor',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='ornament',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_kk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='size',
            name='description_kk',
        ),
        migrations.RemoveField(
            model_name='size',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='name_kk',
        ),
    ]
