# Generated by Django 5.0.7 on 2024-10-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bonus_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена бонусами'),
        ),
    ]
