# Generated by Django 5.0.7 on 2024-10-16 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productsize_options_remove_size_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product_size',
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='product.color', verbose_name='Цвет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/', verbose_name='Изображение'),
        ),
    ]
