# Generated by Django 5.0.7 on 2024-10-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_bonus_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='attributefield',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='formvariant',
            name='attribute_fields',
        ),
        migrations.RemoveField(
            model_name='form',
            name='category',
        ),
        migrations.RemoveField(
            model_name='form',
            name='form_color',
        ),
        migrations.RemoveField(
            model_name='form',
            name='ornaments',
        ),
        migrations.RemoveField(
            model_name='formvariant',
            name='form',
        ),
        migrations.RemoveField(
            model_name='formvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='formvariant',
            name='ornament',
        ),
        migrations.DeleteModel(
            name='OrderRequest',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='AttributeField',
        ),
        migrations.DeleteModel(
            name='FormCategory',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='FormColor',
        ),
        migrations.DeleteModel(
            name='FormVariant',
        ),
        migrations.DeleteModel(
            name='Ornament',
        ),
    ]
