# Generated by Django 5.0.7 on 2024-10-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_formcolor_name_en_formcolor_name_kk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='form',
        ),
        migrations.RemoveField(
            model_name='formcolor',
            name='form',
        ),
        migrations.RemoveField(
            model_name='ornament',
            name='form',
        ),
        migrations.AddField(
            model_name='attribute',
            name='form',
            field=models.ManyToManyField(to='product.form'),
        ),
        migrations.AddField(
            model_name='formcolor',
            name='form',
            field=models.ManyToManyField(to='product.form'),
        ),
        migrations.AddField(
            model_name='ornament',
            name='form',
            field=models.ManyToManyField(to='product.form'),
        ),
    ]
