# Generated by Django 5.0.7 on 2024-10-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_form_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=5.0, verbose_name='Рейтинг'),
        ),
    ]
