# Generated by Django 5.0.7 on 2024-10-10 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_attribute_form_remove_formcolor_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formvariant',
            name='attribute_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.attributefield', verbose_name='Аттрибуты'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FormVariantAttribute',
        ),
    ]
