# Generated by Django 5.0.7 on 2024-10-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_similarproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimilarProduct',
        ),
    ]
