# Generated by Django 5.0.7 on 2024-10-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='Заказан'),
        ),
    ]
