# Generated by Django 5.0.7 on 2024-10-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_formvariant_attribute_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ornament',
            name='form',
            field=models.ManyToManyField(related_name='ornaments', to='product.form'),
        ),
    ]
