# Generated by Django 5.0.7 on 2024-10-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_ornament_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ornament',
            name='form',
        ),
        migrations.AddField(
            model_name='form',
            name='ornaments',
            field=models.ManyToManyField(to='product.ornament'),
        ),
    ]
