# Generated by Django 5.0.7 on 2024-10-16 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_delete_similarproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_products', to='product.product')),
                ('similar_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_similar_products', to='product.product')),
            ],
            options={
                'verbose_name': 'Похожий продукт',
                'verbose_name_plural': 'Похожие продукты',
                'unique_together': {('product', 'similar_product')},
            },
        ),
    ]
