# Generated by Django 5.0.7 on 2024-10-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_reviewimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(default=1, upload_to='product_photos/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
