# Generated by Django 5.0.7 on 2024-10-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_similarproduct'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='similarproduct',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='similarproduct',
            constraint=models.UniqueConstraint(fields=('product', 'similar_product'), name='unique_similar_product'),
        ),
    ]
