# Generated by Django 5.0.7 on 2024-10-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_ornament_form_form_ornaments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='form',
        ),
        migrations.RemoveField(
            model_name='formcolor',
            name='form',
        ),
        migrations.AddField(
            model_name='form',
            name='attribute',
            field=models.ManyToManyField(to='product.attribute'),
        ),
        migrations.AddField(
            model_name='form',
            name='formcolor',
            field=models.ManyToManyField(to='product.formcolor'),
        ),
    ]
