# Generated by Django 5.0.7 on 2024-10-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_attribute_form_remove_formcolor_form_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='formcolor',
            new_name='form_color',
        ),
    ]
