# Generated by Django 5.0.7 on 2024-10-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_slug_alter_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_promoted',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемая'),
        ),
    ]
