# Generated by Django 5.0.7 on 2024-10-12 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_productsize_discounted_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='size',
        ),
        migrations.AddField(
            model_name='productsize',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='product.color', verbose_name='Цвета'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsize',
            name='sizes',
            field=models.ManyToManyField(related_name='product_sizes', to='product.size', verbose_name='Размеры'),
        ),
    ]
