# Generated by Django 5.0.7 on 2024-10-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_productsize_colors_remove_productsize_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product_size',
        ),
        migrations.RemoveField(
            model_name='size',
            name='description',
        ),
        migrations.RemoveField(
            model_name='size',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='size',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='size',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='size',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='size',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='size',
            name='name_ru',
        ),
    ]
