# Generated by Django 5.0.7 on 2024-10-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_category_name_alter_category_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='similar_products',
            field=models.ManyToManyField(blank=True, to='product.product', verbose_name='Похожие продукты'),
        ),
        migrations.DeleteModel(
            name='SimilarProduct',
        ),
    ]
