# Generated by Django 5.0.7 on 2024-10-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_form_ornaments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='ornaments',
            field=models.ManyToManyField(to='product.ornament'),
        ),
    ]
