# Generated by Django 5.0.7 on 2024-10-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_form_ornaments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formvariant',
            name='attribute_field',
        ),
        migrations.AddField(
            model_name='formvariant',
            name='attribute_fields',
            field=models.ManyToManyField(to='product.attributefield', verbose_name='Аттрибуты'),
        ),
    ]
