# Generated by Django 5.0.7 on 2024-10-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_productimage_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='toppings',
        ),
    ]
