# Generated by Django 5.0.7 on 2024-10-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_similar_products_delete_similarproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(upload_to='product_images/', verbose_name='Изображение'),
        ),
    ]
