# Generated by Django 5.0.7 on 2024-10-10 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_formvariant_attribute_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formvariant',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='formvariant',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='formvariant',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='formvariant',
            name='name_ru',
        ),
    ]
