# Generated by Django 5.0.7 on 2024-10-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Мета Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Мета Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_photo',
            field=models.FileField(blank=True, null=True, upload_to='product_photos/', verbose_name='Мета Фото'),
        ),
    ]
