# Generated by Django 5.0.7 on 2024-10-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_formvariant_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер для связи')),
                ('city_region', models.CharField(max_length=255, verbose_name='Город/регион')),
                ('quantity', models.IntegerField(verbose_name='Предполагаемое количество единиц')),
                ('delivery_date', models.DateField(verbose_name='Когда требуется заказ?')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Ваш комментарий')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
