# Generated by Django 5.0.7 on 2024-10-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_country_alter_product_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Страна'),
        ),
    ]
