# Generated by Django 5.0.7 on 2024-10-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_meta_description_product_meta_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name_ky',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
