# Generated by Django 5.0.7 on 2024-10-12 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_country_name_en_country_name_ky_country_name_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Гендер')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Гендер')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Гендер')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Гендер')),
            ],
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='bonus_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.gender', verbose_name='Пол'),
            preserve_default=False,
        ),
    ]
