# Generated by Django 5.0.7 on 2024-10-21 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_datetime_product_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 21, 11, 34, 45, 76528, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления'),
            preserve_default=False,
        ),
    ]
