# Generated by Django 5.0.7 on 2024-10-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_gender_remove_productsize_bonus_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='value_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='value_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='value_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Значение'),
        ),
    ]
