# Generated by Django 5.0.7 on 2024-10-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=models.FileField(null=True, upload_to='product_size_chart', verbose_name="Изображения 'Размерная сетка'"),
        ),
    ]
