# Generated by Django 5.0.7 on 2024-10-22 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_size_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size_chart',
        ),
        migrations.CreateModel(
            name='SizeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='size_charts/', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_charts', to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Размерная сетка',
                'verbose_name_plural': 'Размерные сетки',
            },
        ),
    ]
