# Generated by Django 5.0.7 on 2024-10-22 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_product_size_chart_sizechart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizechart',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.sizechart', verbose_name='Размерная Сетка'),
        ),
    ]
