# Generated by Django 5.0.7 on 2024-10-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_sizechart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='logo',
            field=models.ImageField(upload_to='countries', verbose_name='Флаг Страны'),
        ),
    ]
