# Generated by Django 5.0.7 on 2024-10-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_product_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
