# Generated by Django 5.0.7 on 2024-10-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_productsize_discounted_price_productsize_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='bonus_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена бонусами'),
        ),
    ]
