# Generated by Django 5.0.7 on 2024-11-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, editable=False, max_length=9, verbose_name='Артикул'),
        ),
    ]
