# Generated by Django 5.0.7 on 2024-10-17 11:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_banner_is_top_alter_banner_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('online_payment', models.BooleanField(default=True, verbose_name='Оплата онлайн')),
            ],
            options={
                'verbose_name': 'Доставка и Оплата',
                'verbose_name_plural': 'Доставки и Оплаты',
            },
        ),
    ]
