# Generated by Django 5.0.7 on 2024-10-11 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_staticpage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticpage',
            name='description_kk',
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='title_kk',
        ),
    ]
