# Generated by Django 5.0.7 on 2024-10-17 11:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_deliverypayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryPayment',
        ),
        migrations.RemoveField(
            model_name='methodsofpayment',
            name='image',
        ),
        migrations.AddField(
            model_name='methodsofpayment',
            name='online_payment',
            field=models.BooleanField(default=True, verbose_name='Оплата онлайн'),
        ),
        migrations.AlterField(
            model_name='methodsofpayment',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
