# Generated by Django 5.0.7 on 2024-10-18 04:14

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_methodsofpayment_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('image', models.FileField(upload_to='pages/redirection/', verbose_name='Изображение')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirection', to='pages.mainpage')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
    ]
