# Generated by Django 5.0.7 on 2024-10-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_redirection'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirection',
            name='link_2',
            field=models.URLField(default=1, verbose_name='Дополнительная ссылка'),
            preserve_default=False,
        ),
    ]
