# Generated by Django 5.0.7 on 2024-10-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_methodsofpayment_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='icon',
            field=models.FileField(help_text='Логотип для главной страницы.', upload_to='images/icons', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='image',
            field=models.FileField(blank=True, max_length=5000, null=True, upload_to='images/static', verbose_name='Изображение'),
        ),
    ]
