# Generated by Django 5.0.7 on 2024-10-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_mainpage_icon_alter_staticpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Ключевые слова для SEO', null=True, verbose_name='Ключевые слова (keywords)'),
        ),
    ]
