# Generated by Django 5.0.7 on 2024-10-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_mainpage_meta_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='maintenance',
            field=models.BooleanField(default=False, verbose_name='Технические работы'),
        ),
    ]
