# Generated by Django 5.0.7 on 2024-11-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_mainpage_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='image',
            field=models.ImageField(upload_to='images/stories', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='images/stories', verbose_name='Изображение'),
        ),
    ]
