# Generated by Django 5.0.7 on 2024-10-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_messages',
            field=models.IntegerField(default=0),
        ),
    ]
