# Generated by Django 5.0.7 on 2024-10-28 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_new_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='new_messages',
        ),
    ]
